name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.JS
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - uses: microsoft/playwright-github-action@v1
    - name: build forkphorus
      run: |
        npm ci
        npm run build
    - name: run tests
      run: |
        cd tests
        npm ci
        npm test
